-- SQLite
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS tasks;
DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS tasks (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  id_user INT NOT NULL,
  FOREIGN KEY (id_user) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS users(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  username VARCHAR(40) NOT NULL UNIQUE,
  password VARCHAR(100) NOT NULL
);